/*
This file was automatically generated by joi-to-typescript
Do not modify this file manually
*/

export type passwordSchema = string;

export type usernameDiscrimComboSchema = string;

export type usernameSchema = string;
