/*
This file was automatically generated by joi-to-typescript
Do not modify this file manually
*/

/**
 * The configuration format for the server
 */
export interface config {
	/**
	 * The database specific options
	 */
	database: databaseOptions;
	/**
	 * The web server options
	 */
	server: serverOptions;
	/**
	 * The options relating specifically to the service and it's operations
	 */
	service: serviceOptions;
}

/**
 * The database specific options
 */
export interface databaseOptions {
	/**
	 * The location indicator where the database is. This can be a filepath or a socket URI, depending on what database is being used.
	 */
	uri: string;
}

/**
 * The web server options
 */
export interface serverOptions {
	/**
	 * The port the server will run on
	 */
	port: number;
}

/**
 * The options relating specifically to the service and it's operations
 */
export interface serviceOptions {
	same_name_account_limit: number;
}
